apiVersion: v1
data:
  mapRoles: |2
        - groups:
          - system:bootstrappers
          - system:nodes
          rolearn: arn:aws:iam::721078768257:role/student-r-ms-6-k8s-workernodes-iam-role
          username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |2
        - userarn: arn:aws:iam::721078768257:user/radu.marin
          username: radu.marin
          groups:
            - system:masters
        - userarn: arn:aws:iam::721078768257:user/radu.radau
          username: radu.radau
          groups:
            - system:masters
        - userarn: arn:aws:iam::721078768257:user/adelin.popa
          username: adelin.popa
          groups:
            - system:masters
        - userarn: arn:aws:iam::721078768257:user/matei.serbanescu
          username: matei.serbanescu
          groups:
            - system:masters
        - userarn: arn:aws:iam::721078768257:user/marius.ghebuta
          username: marius.ghebuta
          groups:
            - system:masters
        - userarn: arn:aws:iam::721078768257:user/bogdan.socaciu
          username: bogdan.socaciu
          groups:
            - system:masters
        - userarn: arn:aws:iam::721078768257:user/bogdan.cimpeanu
          username: bogdan.cimpeanu
          groups:
            - system:masters
immutable: false
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"    - groups:\n      - system:bootstrappers\n      - system:nodes\n      rolearn: arn:aws:iam::721078768257:role/student-r-ms-6-k8s-workernodes-iam-role\n      username: system:node:{{EC2PrivateDNSName}}\n","mapUsers":"    - userarn: arn:aws:iam::721078768257:user/radu.marin\n      username: radu.marin\n      groups:\n        - system:masters\n    - userarn: arn:aws:iam::721078768257:user/radu.radau\n      username: radu.radau\n      groups:\n        - system:masters\n    - userarn: arn:aws:iam::721078768257:user/adelin.popa\n      username: adelin.popa\n      groups:\n        - system:masters\n    - userarn: arn:aws:iam::721078768257:user/matei.serbanescu\n      username: matei.serbanescu\n      groups:\n        - system:masters\n    - userarn: arn:aws:iam::721078768257:user/marius.ghebuta\n      username: marius.ghebuta\n      groups:\n        - system:masters\n    - userarn: arn:aws:iam::721078768257:user/bogdan.socaciu\n      username: bogdan.socaciu\n      groups:\n        - system:masters\n    - userarn: arn:aws:iam::721078768257:user/bogdan.cimpeanu\n      username: bogdan.cimpeanu\n      groups:\n        - system:masters\n"},"immutable":false,"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2022-10-28T11:57:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "7888"
  uid: da81102d-73ba-40fc-ba35-5c1c5bc6036e
