apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::721078768257:role/student-r-ms-6-k8s-workernodes-iam-role
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::721078768257:user/radu.marin
      username: radu.marin
      groups:
        - system:masters
    - userarn: arn:aws:iam::721078768257:user/adelin.popa
      username: adelin.popa
      groups:
        - system:masters
    - userarn: arn:aws:iam::721078768257:user/radu.radau
      username: radu.radau
      groups:
        - system:masters
    - userarn: arn:aws:iam::721078768257:user/matei.serbanescu
      username: matei.serbanescu
      groups:
        - system:masters
    - userarn: arn:aws:iam::721078768257:user/bogdan.cimpeanu
      username: matei.serbanescu
      groups:
        - system:masters
    - userarn: arn:aws:iam::721078768257:user/bogdan.socaciu
      username: matei.serbanescu
      groups:
        - system:masterss
    - userarn: arn:aws:iam::721078768257:user/marius.ghebuta
      username: matei.serbanescu
      groups:
        - system:masters

kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system